CREATE TABLE ACTOR(
ID INT(8) auto_increment PRIMARY KEY,
LASTNAME VARCHAR(20) NOT NULL,
FIRSTNAME VARCHAR(20)
);


CREATE TABLE MOVIE(
ID INT(8) auto_increment PRIMARY KEY,
TITLE VARCHAR(50) NOT NULL,
COPIES INT(5) NOT NULL,
MOVIE_TYPE VARCHAR(20) NOT NULL,
MAIN_ACTOR_ID INT(8) NULL
);


ALTER TABLE MOVIE
	ADD CONSTRAINT FK_MAIN_ACTOR
	FOREIGN KEY (MAIN_ACTOR_ID)
	REFERENCES ACTOR(ID);


CREATE TABLE MOVIE_SEC_ACTORS(
ID_MOVIE INT(8) NOT NULL,
ID_ACTOR INT(8) NOT NULL
);

ALTER TABLE MOVIE_SEC_ACTORS 
	ADD CONSTRAINT PK_MOVIE_ACTORS  
	PRIMARY KEY (ID_MOVIE,ID_ACTOR);


ALTER TABLE MOVIE_SEC_ACTORS
	ADD CONSTRAINT FK_MA_MOVIE
	FOREIGN KEY (ID_MOVIE)
	REFERENCES MOVIE(ID);


ALTER TABLE MOVIE_SEC_ACTORS
	ADD CONSTRAINT FK_MA_ACTOR
	FOREIGN KEY (ID_ACTOR)
	REFERENCES ACTOR(ID);